### ISSUE TITLE
Accept ROM Path through std input when not provided

### ISSUE THREAD

**Issue by venkat24** [venkat24/tvp#6]
The ROM file path to open is being inputted as a command line arg through `argv` in `main.cpp`. When this is left empty, the program exits.

This can be improved by giving the user a chance to input the file path after failing to provide one initially. This should involve a change only in `main.cpp`

**Comment by trickarcher** [comment]
Hi, I was just thinking that it would be a good practice to include an exception block in the constructor of the `catridge.cpp` file which would enable a clean exit, instead of a `bad alloc` exception error on the terminal, in case an invalid file_path/file_name is given. 

Also, I modified the `main.cpp` file to input the file path in case the user doesn't specify as a CLI argument. I added an exit option, for now a simple `q` key, in place of the file name would exit `TVP`. I'll submit a merge request for the same, once we discuss about the exception handling case.

**Comment by venkat24** [comment]
Hey @anish0x2a!

Yes, the ```bad_alloc``` should not show up. The underlying cause there is that the filename specified could not be opened. So instead, a simple check for if the file exists before trying to open it should do the trick.

Thanks for your contribution!

**Comment by trickarcher** [comment]
Hey @venkat24, Thanks for the quick follow up. 

I just realized that just checking for the existence of a file if not enough. It might so happen that although a file is exists and opens, it isn't a GB ROM file or even worse the path is a directory. I went on and modified the `cartridge.cpp` and inserted a `try catch block`. Something like this.

```
try  {
  byte_input = std::vector<char>(rom_file_size, '\0');
 }
catch(exception& e) {
  std::cout <<"Error Reading into given ROM file" << endl;
  exit(1);
} 
```
Now, there is another problem. Suppose I enter a file which is not a GB file, what happens is that the tvp emulator boots up and displays a gibberish boot image on the canvas. I guess that's mostly because of the RAM boot sequence, which loads the Nintendo Logo and checks for authenticity. 

I guess a simple check for `.gb` files should do the trick for now.

**Comment by venkat24** [comment]
So, you're right that it will currently open any file, and adding a `.gb` check might be an extra layer of validation, but .gb is not a standard extension, and a GameBoy ROM dump could have any extension.

The right way to validate a ROM file would be to check for the cartridge header. The [Cartridge Header](https://gbdev.gg8.se/wiki/articles/The_Cartridge_Header) is the starting section of the ROM that describes some attributes about the file, such as the name of the game.

This is how we would actually set the title of the window, for example. This is functionality is currently not in the emulator, but it could certainly be useful in the future. As for the scope of this issue, just validating that the file exists and that it is a file should be enough for now.

**Comment by venkat24** [comment]
I've opened up issue #10 for tracking the cartridge header check feature.
